/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public String NomorAkun = "";
    public String myRole = "";
    public String username = "";
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.KoneksiDatabase.BukaKoneksi();
    Color DefaultColor, ClickedColor;

    public Home(String nomorAkun, String role, String username) throws SQLException {
        initComponents();
        setTitle("Aquabank");
        DefaultColor = new Color(78, 202, 255);
        ClickedColor = new Color(128, 217, 255);

        // Set default color to pan on run time
        Menu1.setBackground(ClickedColor);
        Menu2.setBackground(DefaultColor);
        Menu3.setBackground(DefaultColor);
        myRole = role;
        NomorAkun = nomorAkun;
        this.username = username;
        if ("user".equals(role)) {
            handleUserRoleForPanel(role);
        } else {
            Menu1 menu1 = new Menu1(this);
            jPanel2.removeAll();
            jPanel2.add(menu1).setVisible(true);
        }

        role = role.substring(0, 1).toUpperCase() + role.substring(1);
        usernameLabel.setText(username);
        nomorAkunLabel.setText(nomorAkun);
    }
    
    private Home() {}

    private void handleUserRoleForPanel(String role) throws SQLException {
        if ("user".equals(role)) {
            UserHome userHome = new UserHome(this, NomorAkun);
            jPanel2.removeAll();
            jPanel2.add(userHome).setVisible(true);
            LabelMenu1.setText("Dashboard");
            LabelMenu2.setText("Transaksi");
            pageTitle.setText("Dashboard");
        } else if ("admin".equals(role)) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pageTitle = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        Menu1 = new javax.swing.JPanel();
        LabelMenu1 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JPanel();
        LabelMenu2 = new javax.swing.JLabel();
        Menu3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        circlePanel1 = new raven.swing.CirclePanel();
        jLabel1 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        nomorAkunLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyBank");
        setMinimumSize(new java.awt.Dimension(1280, 760));
        setName("Home"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 760));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(78, 202, 255));

        pageTitle.setBackground(new java.awt.Color(0, 0, 0));
        pageTitle.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        pageTitle.setForeground(new java.awt.Color(255, 255, 255));
        pageTitle.setText("Daftar Akun");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pageTitle)
                .addContainerGap(837, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pageTitle)
                .addGap(20, 20, 20))
        );

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1000, 60));

        sidebarPanel.setBackground(new java.awt.Color(78, 202, 255));

        Menu1.setBackground(new java.awt.Color(128, 217, 255));
        Menu1.setForeground(new java.awt.Color(255, 237, 194));
        Menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu1.setPreferredSize(new java.awt.Dimension(232, 44));
        Menu1.setVerifyInputWhenFocusTarget(false);
        Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu1MousePressed(evt);
            }
        });
        Menu1.setLayout(new java.awt.CardLayout(10, 12));

        LabelMenu1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        LabelMenu1.setForeground(new java.awt.Color(255, 255, 255));
        LabelMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/firebank-dashboard.png"))); // NOI18N
        LabelMenu1.setText("Daftar Akun");
        LabelMenu1.setToolTipText("Daftar Akun");
        LabelMenu1.setIconTextGap(8);
        LabelMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelMenu1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelMenu1MousePressed(evt);
            }
        });
        Menu1.add(LabelMenu1, "card2");

        Menu2.setBackground(new java.awt.Color(128, 217, 255));
        Menu2.setForeground(new java.awt.Color(255, 237, 194));
        Menu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu2.setPreferredSize(new java.awt.Dimension(232, 44));
        Menu2.setVerifyInputWhenFocusTarget(false);
        Menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu2MousePressed(evt);
            }
        });
        Menu2.setLayout(new java.awt.CardLayout(10, 12));

        LabelMenu2.setFont(new java.awt.Font("Inter SemiBold", 0, 16)); // NOI18N
        LabelMenu2.setForeground(new java.awt.Color(255, 255, 255));
        LabelMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/firebank-transaction-white.png"))); // NOI18N
        LabelMenu2.setText("Daftar Transaksi");
        LabelMenu2.setToolTipText("Daftar Transaksi");
        LabelMenu2.setIconTextGap(8);
        LabelMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelMenu2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelMenu2MousePressed(evt);
            }
        });
        Menu2.add(LabelMenu2, "card2");

        Menu3.setBackground(new java.awt.Color(128, 217, 255));
        Menu3.setForeground(new java.awt.Color(255, 237, 194));
        Menu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu3.setPreferredSize(new java.awt.Dimension(232, 44));
        Menu3.setVerifyInputWhenFocusTarget(false);
        Menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu3MouseClicked(evt);
            }
        });
        Menu3.setLayout(new java.awt.CardLayout(10, 12));

        jLabel3.setFont(new java.awt.Font("Inter SemiBold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/firebank-logout-WHITE.png"))); // NOI18N
        jLabel3.setText("Logout");
        jLabel3.setToolTipText("");
        jLabel3.setIconTextGap(8);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        Menu3.add(jLabel3, "card2");

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Aquabank");

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logos/WHITE-Firebank_Logo_33x54.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(78, 202, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        circlePanel1.setBackground(new java.awt.Color(255, 255, 255));
        circlePanel1.setLayout(new java.awt.FlowLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/firebank-profile-30x30.png"))); // NOI18N
        circlePanel1.add(jLabel1);

        jPanel3.add(circlePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Inter SemiBold", 0, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Kreshna Dhana");
        usernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, -1));

        nomorAkunLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        nomorAkunLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomorAkunLabel.setText("7384783274");
        nomorAkunLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(nomorAkunLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, -1));

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Menu2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                .addComponent(Menu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Menu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        mainPanel.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 720));

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 670));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 1000, 670));

        getContentPane().add(mainPanel, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MousePressed
        Menu1.setBackground(ClickedColor);
        Menu2.setBackground(DefaultColor);
        Menu3.setBackground(DefaultColor);
    }//GEN-LAST:event_Menu1MousePressed

    private void Menu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MousePressed
        Menu1.setBackground(DefaultColor);
        Menu2.setBackground(ClickedColor);
        Menu3.setBackground(DefaultColor);
    }//GEN-LAST:event_Menu2MousePressed

    private void LabelMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMenu1MousePressed
        Menu1.setBackground(ClickedColor);
        Menu2.setBackground(DefaultColor);
        Menu3.setBackground(DefaultColor);
    }//GEN-LAST:event_LabelMenu1MousePressed

    private void LabelMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMenu1MouseClicked
        if ("user".equals(myRole)) {
            UserHome userHome = null;
            try {
                userHome = new UserHome(this, NomorAkun);
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            jPanel2.removeAll();
            jPanel2.add(userHome).setVisible(true);
            pageTitle.setText("Home");
        } else {
            Menu1 menu1 = new Menu1(this);
            jPanel2.removeAll();
            jPanel2.add(menu1).setVisible(true);
            pageTitle.setText("Daftar Akun");
        }
    }//GEN-LAST:event_LabelMenu1MouseClicked

    private void Menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseClicked
        if ("user".equals(myRole)) {
            pageTitle.setText("Home");
        } else {
            Menu1 menu1 = new Menu1(this);
            jPanel2.removeAll();
            jPanel2.add(menu1).setVisible(true);
            pageTitle.setText("Daftar Akun");
        }

    }//GEN-LAST:event_Menu1MouseClicked

    private void LabelMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMenu2MousePressed
        Menu1.setBackground(DefaultColor);
        Menu2.setBackground(ClickedColor);
        Menu3.setBackground(DefaultColor);
    }//GEN-LAST:event_LabelMenu2MousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });

        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void Menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu3MouseClicked

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });

        this.dispose();
    }//GEN-LAST:event_Menu3MouseClicked

    private void LabelMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMenu2MouseClicked
        if ("user".equals(myRole)) {
//            MenuUser2 menuUser2 = new MenuUser2(this);
//            jPanel2.removeAll();
//            jPanel2.add(menuUser2).setVisible(true);
            pageTitle.setText("Transaksi Saya");
        } else {
//            Menu2 menu2 = new Menu2(this);
//            jPanel2.removeAll();
//            jPanel2.add(menu2).setVisible(true);

        }
    }//GEN-LAST:event_LabelMenu2MouseClicked

    private void Menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MouseClicked
        if ("user".equals(myRole)) {
//            MenuUser2 menuUser2 = new MenuUser2(this);
//            jPanel2.removeAll();
//            jPanel2.add(menuUser2).setVisible(true);
            pageTitle.setText("Transaksi Saya");
        } else {
//            Menu2 menu2 = new Menu2(this);
//            jPanel2.removeAll();
//            jPanel2.add(menu2).setVisible(true);

        }
    }//GEN-LAST:event_Menu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMenu1;
    private javax.swing.JLabel LabelMenu2;
    private javax.swing.JPanel Menu1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JPanel Menu3;
    private raven.swing.CirclePanel circlePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nomorAkunLabel;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
