/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form;

import java.util.regex.*;
import form.user.Deposit;
import form.user.Transfer;

/**
 *
 * @author User
 */
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import raven.cell.TableActionCellEditor;
import raven.cell.TableActionCellRender;
import raven.cell.TableActionEvent;

public class UserHome extends javax.swing.JInternalFrame {

    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.KoneksiDatabase.BukaKoneksi();
    JFrame parentComponent;
    String NomorAkun;

    /**
     * Creates new form Menu1
     *
     * @param parentComponentParam
     * @param nomorAkun
     * @throws java.sql.SQLException
     */
    public UserHome(JFrame parentComponentParam, String nomorAkun) throws SQLException {
        parentComponent = parentComponentParam;
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        NomorAkun = nomorAkun;
        
        st = cn.createStatement();
    }

    private void Deposit(String nomorAkun, double jumlah) throws SQLException {
        ResultSet result = getAccount(nomorAkun);

        if (result != null) {
            double currentBalance = getBalance(nomorAkun);
            double totalBalance = currentBalance + jumlah;
            String query = "UPDATE user SET balance = ? WHERE no_akun = ?";
            PreparedStatement statement = cn.prepareStatement(query);
            statement.setDouble(1, totalBalance);
            statement.setString(2, nomorAkun);
            statement.execute();

            JOptionPane.showMessageDialog(null, "Berhasil Deposit!");
            
            balanceLabel.setText(Double.toString(totalBalance));
        } else {
            System.out.println("ADDING NEW USER!");
            String query = "INSERT INTO user (no_akun, balance) VALUES (?, ?)";
            PreparedStatement statement = cn.prepareStatement(query);
            statement.setString(1, nomorAkun);
            statement.setDouble(2, jumlah);

            statement.execute();
            JOptionPane.showMessageDialog(null, "Berhasil deposit!");
            
            balanceLabel.setText(Double.toString(jumlah));
        }
    }

    public double getBalance(String nomorAkun) throws SQLException {

        String query = "SELECT balance FROM user WHERE no_akun = '" + nomorAkun + "'";
        rs = st.executeQuery(query);
        double balance = 0;
        if (rs.next()) {
            balance = rs.getDouble("balance");
        }
        return balance;
    }

    public ResultSet getAccount(String nomorAkun) throws SQLException {
        String query = "SELECT * FROM user WHERE no_akun = '" + nomorAkun + "'";

        rs = st.executeQuery(query);
        ResultSet result = null;
        if (rs.next()) {
            result = rs;
        } else {
            JOptionPane.showMessageDialog(null, "Maaf, akun tidak ditemukan!");
        }
        return result;
    }

    private double Withdraw(String nomorAkun, double jumlahYangAkanDitarik) throws SQLException {
        double balance = getBalance(nomorAkun);
        double newBalance = balance - jumlahYangAkanDitarik;

        if (newBalance < 0) {
            JOptionPane.showMessageDialog(null, "Kebanyakan wdnya woi!");
        } else {
            String query = "UPDATE user SET balance = ? WHERE no_akun = ?";
            PreparedStatement statement = cn.prepareStatement(query);

            statement.setDouble(1, newBalance);
            statement.setString(2, nomorAkun);
            statement.execute();
            balanceLabel.setText(Double.toString(newBalance));
        }
        return newBalance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pengeluaranLabel = new javax.swing.JLabel();
        depositLabel1 = new javax.swing.JLabel();
        pengeluaranPercentageLabel = new javax.swing.JLabel();
        pengeluaranBulanLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pemasukanLabel = new javax.swing.JLabel();
        depositLabel5 = new javax.swing.JLabel();
        pemasukanPercentageLabel = new javax.swing.JLabel();
        pemasukanBulanLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        depositLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        depositLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        withdrawLabel3 = new javax.swing.JLabel();
        transaksiTertundaLabel = new javax.swing.JLabel();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        totalTransaksiLabel = new javax.swing.JLabel();
        depositLabel11 = new javax.swing.JLabel();
        pemasukanPercentageLabel1 = new javax.swing.JLabel();
        depositLabel12 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table1 = new raven.swing.Table();

        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 670));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 224, 255));
        jPanel2.setForeground(new java.awt.Color(255, 188, 98));

        pengeluaranLabel.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        pengeluaranLabel.setForeground(new java.awt.Color(70, 70, 70));
        pengeluaranLabel.setText("Rp 0");

        depositLabel1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        depositLabel1.setForeground(new java.awt.Color(70, 70, 70));
        depositLabel1.setText("Pengeluaran");

        pengeluaranPercentageLabel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pengeluaranPercentageLabel.setForeground(new java.awt.Color(70, 70, 70));
        pengeluaranPercentageLabel.setText("+0%");

        pengeluaranBulanLabel.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        pengeluaranBulanLabel.setForeground(new java.awt.Color(100, 100, 100));
        pengeluaranBulanLabel.setText("n/a");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pengeluaranBulanLabel)
                    .addComponent(depositLabel1)
                    .addComponent(pengeluaranPercentageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengeluaranLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(depositLabel1)
                .addGap(1, 1, 1)
                .addComponent(pengeluaranBulanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(pengeluaranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengeluaranPercentageLabel)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 150));

        jPanel3.setBackground(new java.awt.Color(178, 232, 255));
        jPanel3.setForeground(new java.awt.Color(5, 5, 5));

        pemasukanLabel.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        pemasukanLabel.setForeground(new java.awt.Color(60, 60, 60));
        pemasukanLabel.setText("Rp 0");

        depositLabel5.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        depositLabel5.setForeground(new java.awt.Color(60, 60, 60));
        depositLabel5.setText("Pemasukan");

        pemasukanPercentageLabel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pemasukanPercentageLabel.setForeground(new java.awt.Color(60, 60, 60));
        pemasukanPercentageLabel.setText("+0%");

        pemasukanBulanLabel.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        pemasukanBulanLabel.setForeground(new java.awt.Color(100, 100, 100));
        pemasukanBulanLabel.setText("n/a");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pemasukanBulanLabel)
                    .addComponent(depositLabel5)
                    .addComponent(pemasukanPercentageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pemasukanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(depositLabel5)
                .addGap(1, 1, 1)
                .addComponent(pemasukanBulanLabel)
                .addGap(18, 18, 18)
                .addComponent(pemasukanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pemasukanPercentageLabel)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 210, 150));

        jPanel5.setBackground(new java.awt.Color(252, 252, 252));

        depositLabel8.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        depositLabel8.setForeground(new java.awt.Color(160, 160, 160));
        depositLabel8.setText("Balance");
        depositLabel8.setMaximumSize(new java.awt.Dimension(60, 18));
        depositLabel8.setMinimumSize(new java.awt.Dimension(60, 18));
        depositLabel8.setPreferredSize(new java.awt.Dimension(60, 18));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(depositLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(depositLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 50));

        jPanel6.setBackground(new java.awt.Color(252, 252, 252));

        depositLabel9.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        depositLabel9.setForeground(new java.awt.Color(160, 160, 160));
        depositLabel9.setText("Utang");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(depositLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(depositLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 70, -1));

        jPanel4.setBackground(new java.awt.Color(252, 252, 252));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(237, 237, 237), 2, true));
        jPanel4.setForeground(new java.awt.Color(5, 5, 5));

        balanceLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(75, 75, 75));
        balanceLabel.setText("Rp 0");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        withdrawLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        withdrawLabel3.setForeground(new java.awt.Color(51, 204, 0));
        withdrawLabel3.setText("+0%");

        transaksiTertundaLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        transaksiTertundaLabel.setForeground(new java.awt.Color(75, 75, 75));
        transaksiTertundaLabel.setText("Rp 0");

        depositButton.setBackground(new java.awt.Color(254, 254, 254));
        depositButton.setFont(new java.awt.Font("Inter ExtraBold", 1, 14)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.setToolTipText("Deposit");
        depositButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        depositButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depositButton.setFocusable(false);
        depositButton.setMaximumSize(new java.awt.Dimension(75, 20));
        depositButton.setMinimumSize(new java.awt.Dimension(75, 20));
        depositButton.setPreferredSize(new java.awt.Dimension(75, 20));
        depositButton.setRequestFocusEnabled(false);
        depositButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositButtonMouseClicked(evt);
            }
        });
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        withdrawButton.setBackground(new java.awt.Color(254, 254, 254));
        withdrawButton.setFont(new java.awt.Font("Inter ExtraBold", 1, 14)); // NOI18N
        withdrawButton.setText("Withdraw");
        withdrawButton.setToolTipText("Withdraw");
        withdrawButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        withdrawButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdrawButton.setFocusable(false);
        withdrawButton.setRequestFocusEnabled(false);
        withdrawButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawButtonMouseClicked(evt);
            }
        });
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        transferButton.setBackground(new java.awt.Color(254, 254, 254));
        transferButton.setFont(new java.awt.Font("Inter ExtraBold", 1, 14)); // NOI18N
        transferButton.setText("Transfer");
        transferButton.setToolTipText("Transfer");
        transferButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        transferButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferButton.setFocusable(false);
        transferButton.setRequestFocusEnabled(false);
        transferButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transferButtonMousePressed(evt);
            }
        });
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(transaksiTertundaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transaksiTertundaLabel)
                            .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(balanceLabel)
                            .addGap(1, 1, 1)
                            .addComponent(withdrawLabel3))))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 940, 80));

        jPanel7.setBackground(new java.awt.Color(204, 240, 255));
        jPanel7.setForeground(new java.awt.Color(5, 5, 5));

        totalTransaksiLabel.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        totalTransaksiLabel.setText("0");

        depositLabel11.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        depositLabel11.setText("Total Transaksi");

        pemasukanPercentageLabel1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pemasukanPercentageLabel1.setForeground(new java.awt.Color(60, 60, 60));
        pemasukanPercentageLabel1.setText("+0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pemasukanPercentageLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depositLabel11)
                            .addComponent(totalTransaksiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(depositLabel11)
                .addGap(37, 37, 37)
                .addComponent(totalTransaksiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pemasukanPercentageLabel1)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 210, 150));

        depositLabel12.setFont(new java.awt.Font("Montserrat Medium", 0, 20)); // NOI18N
        depositLabel12.setForeground(new java.awt.Color(75, 75, 75));
        depositLabel12.setText("Riwayat Transaksi");
        jPanel1.add(depositLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 241, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Target", "Type", "Date", "Amount", "Status"
            }
        ));
        spTable.setViewportView(table1);

        jPanel1.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 940, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawButtonMouseClicked
        TambahAkun tambahAkun = new TambahAkun(cn);
        parentComponent.setEnabled(false);
        tambahAkun.setVisible(true);

        tambahAkun.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                parentComponent.setEnabled(true);
                parentComponent.toFront();
            }
        });

        parentComponent.setVisible(true);

        tambahAkun.toFront();
    }//GEN-LAST:event_withdrawButtonMouseClicked

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        
    }//GEN-LAST:event_depositButtonActionPerformed

    private void depositButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositButtonMouseClicked
        Deposit depositWindow = new Deposit(cn, NomorAkun);
        parentComponent.setEnabled(false);
        depositWindow.setVisible(true);

        depositWindow.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                parentComponent.setEnabled(true);
                parentComponent.toFront();
            }
        });

        parentComponent.setVisible(true);

        depositWindow.toFront();
    }//GEN-LAST:event_depositButtonMouseClicked

    private void transferButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_transferButtonMouseClicked

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferButtonActionPerformed

    private void transferButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferButtonMousePressed
        Transfer transferWindow = new Transfer(cn, NomorAkun);
        parentComponent.setEnabled(false);
        transferWindow.setVisible(true);

        transferWindow.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                parentComponent.setEnabled(true);
                parentComponent.toFront();
            }
        });

        parentComponent.setVisible(true);

        transferWindow.toFront();
    }//GEN-LAST:event_transferButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel depositLabel1;
    private javax.swing.JLabel depositLabel11;
    private javax.swing.JLabel depositLabel12;
    private javax.swing.JLabel depositLabel5;
    private javax.swing.JLabel depositLabel8;
    private javax.swing.JLabel depositLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pemasukanBulanLabel;
    private javax.swing.JLabel pemasukanLabel;
    private javax.swing.JLabel pemasukanPercentageLabel;
    private javax.swing.JLabel pemasukanPercentageLabel1;
    private javax.swing.JLabel pengeluaranBulanLabel;
    private javax.swing.JLabel pengeluaranLabel;
    private javax.swing.JLabel pengeluaranPercentageLabel;
    private javax.swing.JScrollPane spTable;
    private raven.swing.Table table1;
    private javax.swing.JLabel totalTransaksiLabel;
    private javax.swing.JLabel transaksiTertundaLabel;
    private javax.swing.JButton transferButton;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JLabel withdrawLabel3;
    // End of variables declaration//GEN-END:variables
}
